### ISSUE TITLE
AWStats delete_feature is never called upon server deletion

### ISSUE THREAD

**Issue by iliaross** [virtualmin/virtualmin-awstats#1]
Jamie, hi.

Having latest package version 5.11 installed. When deleting virtual server, AWStats records are not actually getting deleted. However, when you enable/disable feature from **Edit Virtual Server** page - it works as expected.

The problem is that after virtual server is deleted, records in AWStats module are still there.

**Comment by jcameron** [comment]
Do you mean that the domain's config file in `/etc/awstats` still exist even if a domain is created and then delete?

**Comment by jcameron** [comment]
Ok I see the bug - it's actually in Virtualmin, and will be fixed in the next release.

**Comment by iliaross** [comment]
Thanks, Jamie. I'll check I out.

**Comment by iliaross** [comment]
Works fine. Thanks!
