### ISSUE TITLE
Nginx: AWStats aren't working

### ISSUE THREAD

**Issue by iliaross** [virtualmin/virtualmin-awstats#11]
Jamie, when AWStats setup with Nginx, it simply not working neither when we visit `example.com/awstats` nor `example.com/awstats.pl`. For the latter though, it returns 404 Not Found error but for the former 403 Forbidden error.

Additionally, there are no any extra records added to Nginx config.

**Comment by jcameron** [comment]
What about if you try /awstats/awstats.pl ?

**Comment by iliaross** [comment]
> What about if you try /awstats/awstats.pl ?

The error 404 is returned.

**Comment by jcameron** [comment]
Ok I see the bug that causes this ... I'll look into a fix. What does work is /cgi-bin/awstats.pl

**Comment by jcameron** [comment]
Ok this will be fixed in the next release of the AWstats plugin...
