### ISSUE TITLE
AWStats: Adds records even when fails

### ISSUE THREAD

**Issue by iliaross** [virtualmin/virtualmin-awstats#8]
If AWStats is added as a feature and it fails, like [here](https://github.com/webmin/webmin/issues/1587#issuecomment-1025604547), then the records in **`/etc/awstats`** and in **`/etc/webmin/virtualmin-awstats/runas`** _**are still created**_!

Later it **will _not_ be possible** to restore a domain with the same name or even simply enable this feature for the domain.

This is clearly a bug.

If it fails, no records must be created.

**Comment by jcameron** [comment]
Can you post a screenshot showing at what point adding AWstats failed?

**Comment by iliaross** [comment]
Yes, all the screenshot were posted [here](https://github.com/webmin/webmin/issues/1587#issuecomment-1025604547).

Let me copy/paste it:

![image](https://user-images.githubusercontent.com/4426533/152055449-fa57671c-c946-4d1d-a425-cfba3f3abb0b.png)

(this happened upon domain creation time)

This can be easily reproduced by setting for **`tempdir`** something like:

```
tempdir=/tmp/webmin a'"lternative '   "  tmp**$%$
```

... and not applying my latest patches with `quotemeta` escapes to cron Webmin module.

**Comment by jcameron** [comment]
Ok, so this will be fixed already..

What error did you get when you tried to re-enable AWstats?

**Comment by iliaross** [comment]
> Ok, so this will be fixed already..

Well, the error that made it fail in that case scenario (escaping) - yes, fixed. But if it fails for another reason, then records are going to be added on error again, and it won't be possible to add AWStats unless clearing manually (and you need to know what to clear).

> What error did you get when you tried to re-enable AWstats?

It was saying - already enabled, and skipping it (when editing virtual server) and it was simply failing on restore, saying that records already exist.

It needs to either overwrite those (may be) or make sure that records are never added on failure and/or cleared if domain restore fails completely.

**Comment by jcameron** [comment]
I think the right fix is to never fail the AWstats setup once it starts, so that there's no mismatch between what Virtualmin expects and what config exists.

**Comment by iliaross** [comment]
I don't understand why. The problem is that it may fail, right? And if it does, what is next? You try to enable AWStats and get in return super confusing error saying that it was already enabled?

Also, I remember in the past, which happened many times, if virtual server restore was failing you would get this issue next time trying to restore the same virtual server?

Perhaps, just overwriting would be a solution, without failing? There is not much of important data that could be lost when overwritten, right?

**Comment by jcameron** [comment]
The problem with over-writing is that we don't want to ever delete any AWstats configuration that the user created manually for the same domain name.

**Comment by iliaross** [comment]
Jamie, either way, don't you think we should clear partially created records on error?

**Comment by jcameron** [comment]
Yes, I found one case where this could happen ... I'll submit a change to clean it up.

**Comment by iliaross** [comment]
Wonderful, thank you! `runas` file won't be a problem too on failed setup?

**Comment by jcameron** [comment]
No, that file always just gets overwritten
